// Ponto único de importação da camada de API.
// Ex.: import { authApi, http, ApiError } from '@/api';
export * from './client';
export * from './auth';
export * from './adapters';
export * from './terminals';
export * from './geocoding';
export * from './users';
export * from './entities';
export * from './permissions';
export * from './notification-rules';
export * from './occurrences';
export * from './dashboard';
export * from './entity-notifications';
export * from './chat';
export * from './pae-resources';
export * from './safety';
export * from './audit';
export * from './realtime';
export * from './hooks';
